spring:
  datasource:
    username: deepak
    password: demo@123
    url: jdbc:mysql://localhost:3306/digi_cart
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true